//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesGallery
    {
        public int ID { get; set; }
        public string ImageDescription { get; set; }
        public string ImagePath { get; set; }
        public bool Visible { get; set; }
        public decimal Order { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
