//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDBEntities : DbContext
    {
        public WebDBEntities()
            : base("name=WebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalendarEvent> CalendarEvents { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<HotUpdate> HotUpdates { get; set; }
        public virtual DbSet<ImagesGallery> ImagesGalleries { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<PressReview> PressReviews { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
    }
}
